apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-volume
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-flask
  labels:
    app: api-flask
    group: api-group
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-flask
  template:
    metadata:
      labels:
        app: api-flask
        group: api-group
    spec:
      containers:
        - name: api-flask
          image: api_flask:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: api-flask-port
          env:
            - name: FLASK_APP
              value: main
          volumeMounts:
            - name: api-volume-storage
              mountPath: /data/resources
      volumes:
      - name: api-volume-storage
        persistentVolumeClaim:
          claimName: api-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: api-flask
  labels:
    group: api-group
spec:
  type: NodePort
  selector:
    app: api-flask
  ports:
    - name: http
      port: 5000
      targetPort: 5000